defaults: &defaults
  notify:
    - "#DESC#だよ！薬飲んだ？ by カプ君"
    - "#DESC#だぞ！飲まないとやばいぞ！ by タブ君"
    - "#DESC#になったよ。薬はもう飲んだかな？ by カプ君"
    - "#DESC#になったぞ！薬はもう飲んだか？ by タブ君"
    - "#DESC#だね。薬飲むの忘れちゃだめだよ！ by カプ君"
    - "#DESC#だな。薬飲むの忘れるなよ！ by タブ君"
  tips:
    - "お薬リマインダーソフトTasquel（たすけーる）のTwitterボットです。薬を飲む時間に通知tweetをするよ！ by カプ君"
    - "Tasquel（たすけーる）を利用したければ、Webサイトにログインしてね。 by カプ君"
    - "TasquelのWebサイトへはTwitterアカウントでログインできるぞ！ by タブ君"
    - "薬を飲むだいたいの時間をWebサイトで登録してくれれば、その時間にメンションを送るぞ。 by タブ君"
    - "薬を飲んだら、僕らが送った通知のtweetに返信をしてね！お薬を飲んだ履歴を記録するよ。 by カプ君"
    - "TasquelのWebサイトで、薬があと何日分あるか登録すると、薬の残りが少なくなったときに通知するよ。 by カプ君"
    - "通知のTweetをしてほしかったら、TasqeuelのWebサイトで通知をONにしてこのアカウントをフォローしてね！ by カプ君"   
    - "カプセルのキャラがカプ君、タブレットのほうのキャラがタブ君だよ！おぼえてね。 by カプ君"   
    
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults